dist: xenial

branches:
  only:
    - master
    # Github release tags (for example "v0.9" or "v0.9.1").
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # Branch names endings with "-release" (for example "0.9.0-release").
    - /-release$/

language: rust
rust:
  - 1.37.0
cache:
  - cargo

env:
  global:
    - CARGO_INCREMENTAL=1
    - DEADLINKS_VERS=0.3.0

install:
  - cargo deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
  - rustup component add rustfmt
  - rustfmt -V
  - rustup component add clippy
  - cargo clippy -V

script:
  - cargo fmt -- --check
  - cargo clippy --tests --examples -- -D warnings
  - cargo check --tests --examples
  - cargo test --lib --tests
  - cargo test --doc
  - cargo run --no-default-features --features rand-06,rand --example ed25519 > /dev/null
  - cargo clean --doc && cargo doc --no-deps && cargo deadlinks --dir target/doc

deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
