[package]
name = "secret-tree"
edition = "2018"
version = "0.2.0"
authors = [
  "Alex Ostrovski <ostrovski.alex@gmail.com>",
  "Pavel Mukhanov <mukhanovpv@gmail.com>",
]
license = "Apache-2.0"
keywords = ["derivation", "blake2b", "cryptography"]
readme = "README.md"
categories = ["cryptography", "no-std"]
description = "Hierarchical secret derivation with Blake2b"
repository = "https://github.com/slowli/secret-tree"
documentation = "https://docs.rs/secret-tree/"

[dependencies]
byteorder = "1.3.4"
clear_on_drop = "0.2.3"
blake2-rfc = "0.2.18"
rand = "0.7.3"
rand_chacha = "0.2.2"

[dev-dependencies]
hex = "0.4.2"
ed25519 = { package = "ed25519-dalek", version = "=1.0.0-pre.3" }
pwbox = { version = "0.3.0", default-features = false, features = ["rust-crypto"] }
toml = "0.5.6"

[[example]]
name = "ed25519"
path = "examples/ed25519.rs"
